name: "Action Artifactory CLI"
description: "Uses a multi-step process to run JFrog CLI commands"
runs:
    using: "composite"
    steps:
      - name: Download JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
      - name: print
        uses: echo "this is a test"
        shell: bash
      #- name: Ping JFrog Server
        #run: jfrog rt ping --url ${{ secrets.ARTIFACTORY_URL }} --access-token ${{ secrets.ARTIFACTORY_TOKEN }}
        #shell: bash
      - name: Upload test artifact
        run: jf rt u ${{ env.IMAGE_FILEPATH }} l-docker-testing/${{ env.APPLICATION_CI }}/${{ github.event.repository.name }}/ --dry-run --url ${{ secrets.ARTIFACTORY_URL }} --access-token ${{ secrets.ARTIFACTORY_TOKEN }}
        shell: bash
